"""Unit tests for NetworkInterventionEngine tc band bug fix.

Status: IMPLEMENTED / MAC_TESTED / READY_FOR_LINUX

These tests verify the structural validity of tc commands generated by the
intervention engine. No actual kernel tc execution occurs; all commands are
intercepted in dry_run mode.

The bug: tc_handle="10:" generated parent 1:10, which is invalid for a prio
qdisc (valid bands: 1:1, 1:2, 1:3 only).

Fix: tc_handle must be "1:", "2:", or "3:" — validated in __post_init__.
"""
from __future__ import annotations

import uuid
from unittest.mock import MagicMock, patch, call
import subprocess

import pytest

from src.rift.intervention.network_intervention import (
    NetworkInterventionEngine,
    NetworkInterventionRecord,
    NetworkInterventionSpec,
    NetworkInterventionStatus,
    _VALID_PRIO_BANDS,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_record(
    tc_handle: str = "1:",
    latency_ms: float = 200.0,
    jitter_ms: float = 5.0,
    packet_loss_pct: float = 0.0,
    destination_ip: str = "10.0.0.1",
    interface: str = "eth0",
) -> NetworkInterventionRecord:
    return NetworkInterventionRecord(
        record_id=str(uuid.uuid4()),
        source_service="frontend",
        destination_service="checkout",
        destination_ip=destination_ip,
        interface=interface,
        latency_ms=latency_ms,
        jitter_ms=jitter_ms,
        packet_loss_pct=packet_loss_pct,
        tc_handle=tc_handle,
        tc_parent="1:",
    )


def _extract_cmds(mock_run_cmd) -> list[list[str]]:
    """Return the list of command lists passed to _run_cmd."""
    return [c[0][0] for c in mock_run_cmd.call_args_list]


# ---------------------------------------------------------------------------
# T3-a: Valid band handles accepted, invalid rejected at construction
# ---------------------------------------------------------------------------

class TestBandValidation:
    def test_valid_band_1(self):
        rec = _make_record(tc_handle="1:")
        assert rec.tc_handle == "1:"

    def test_valid_band_2(self):
        rec = _make_record(tc_handle="2:")
        assert rec.tc_handle == "2:"

    def test_valid_band_3(self):
        rec = _make_record(tc_handle="3:")
        assert rec.tc_handle == "3:"

    def test_invalid_band_10_raises(self):
        """The original bug: handle '10:' must now be rejected."""
        with pytest.raises(ValueError, match="1:1, 1:2, 1:3"):
            _make_record(tc_handle="10:")

    def test_invalid_band_20_raises(self):
        with pytest.raises(ValueError, match="valid range"):
            _make_record(tc_handle="20:")

    def test_invalid_band_0_raises(self):
        with pytest.raises(ValueError, match="valid range"):
            _make_record(tc_handle="0:")

    def test_non_numeric_handle_raises(self):
        with pytest.raises(ValueError):
            _make_record(tc_handle="abc:")

    def test_spec_valid_bands_accepted(self):
        for band in (1, 2, 3):
            spec = NetworkInterventionSpec(
                source_service="svc_a",
                destination_service="svc_b",
                destination_ip="10.0.0.1",
                interface="eth0",
                latency_ms=100.0,
                prio_band=band,
            )
            assert spec.prio_band == band
            assert spec.tc_band_str == f"{band}:"
            assert spec.tc_flowid == f"1:{band}"

    def test_spec_invalid_band_raises(self):
        with pytest.raises(ValueError, match="prio_band"):
            NetworkInterventionSpec(
                source_service="svc_a",
                destination_service="svc_b",
                destination_ip="10.0.0.1",
                interface="eth0",
                latency_ms=100.0,
                prio_band=10,  # invalid
            )


# ---------------------------------------------------------------------------
# T3-b: Latency injection command structure
# ---------------------------------------------------------------------------

class TestLatencyInjectionCommandStructure:
    def test_apply_generates_three_commands(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:", latency_ms=200.0)

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)
        assert mock_run.call_count == 3

    def test_apply_uses_correct_band_in_parent(self):
        """netem parent must be 1:<band>, not 1:10 or similar."""
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="2:", latency_ms=100.0)

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)

        cmds = _extract_cmds(mock_run)
        netem_cmd = cmds[1]  # second command: tc qdisc add ... netem
        # parent 1:2 must be in the command
        assert "parent" in netem_cmd
        parent_idx = netem_cmd.index("parent")
        assert netem_cmd[parent_idx + 1] == "1:2"

    def test_apply_uses_correct_band_as_handle(self):
        """netem handle must be <band>:, not 10: or similar."""
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="2:", latency_ms=100.0)

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)

        cmds = _extract_cmds(mock_run)
        netem_cmd = cmds[1]
        handle_idx = netem_cmd.index("handle")
        assert netem_cmd[handle_idx + 1] == "2:"

    def test_apply_filter_uses_correct_flowid(self):
        """u32 filter flowid must be 1:<band>."""
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="3:", latency_ms=50.0)

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)

        cmds = _extract_cmds(mock_run)
        filter_cmd = cmds[2]  # third command: tc filter add
        flowid_idx = filter_cmd.index("flowid")
        assert filter_cmd[flowid_idx + 1] == "1:3"

    def test_apply_sets_correct_latency_in_netem(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:", latency_ms=200.0, jitter_ms=10.0)

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)

        cmds = _extract_cmds(mock_run)
        netem_cmd = cmds[1]
        delay_idx = netem_cmd.index("delay")
        assert netem_cmd[delay_idx + 1] == "200.0ms"
        assert netem_cmd[delay_idx + 2] == "10.0ms"

    def test_apply_sets_status_applied(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:")
        result = engine.apply(rec)
        assert result.status == NetworkInterventionStatus.APPLIED

    def test_all_three_valid_bands_generate_structurally_valid_commands(self):
        """All bands 1, 2, 3 must produce commands that reference valid prio targets."""
        engine = NetworkInterventionEngine(dry_run=True)
        for band in (1, 2, 3):
            rec = _make_record(tc_handle=f"{band}:", latency_ms=100.0)
            with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
                engine.apply(rec)
            cmds = _extract_cmds(mock_run)
            # parent in netem command must be 1:<band>
            netem_cmd = cmds[1]
            parent_idx = netem_cmd.index("parent")
            assert netem_cmd[parent_idx + 1] == f"1:{band}"


# ---------------------------------------------------------------------------
# T3-c: Packet loss command structure
# ---------------------------------------------------------------------------

class TestPacketLossCommandStructure:
    def test_loss_appears_in_netem_command(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:", packet_loss_pct=1.5)

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)

        cmds = _extract_cmds(mock_run)
        netem_cmd = cmds[1]
        loss_idx = netem_cmd.index("loss")
        assert netem_cmd[loss_idx + 1] == "1.50%"


# ---------------------------------------------------------------------------
# T3-d: Destination isolation (per-destination filter)
# ---------------------------------------------------------------------------

class TestDestinationIsolation:
    def test_u32_filter_targets_destination_ip(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:", destination_ip="192.168.1.100")

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)

        cmds = _extract_cmds(mock_run)
        filter_cmd = cmds[2]
        dst_idx = filter_cmd.index("dst")
        assert filter_cmd[dst_idx + 1] == "192.168.1.100/32"

    def test_u32_filter_uses_ip_protocol(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:")

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.apply(rec)

        cmds = _extract_cmds(mock_run)
        filter_cmd = cmds[2]
        assert "protocol" in filter_cmd
        proto_idx = filter_cmd.index("protocol")
        assert filter_cmd[proto_idx + 1] == "ip"


# ---------------------------------------------------------------------------
# T3-e: Rollback command structure
# ---------------------------------------------------------------------------

class TestRollbackCommandStructure:
    def test_rollback_generates_two_commands(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:")
        rec.status = NetworkInterventionStatus.APPLIED

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.rollback(rec)

        assert mock_run.call_count == 2

    def test_rollback_filter_uses_correct_flowid(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="2:")
        rec.status = NetworkInterventionStatus.APPLIED

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.rollback(rec)

        cmds = _extract_cmds(mock_run)
        filter_del = cmds[0]
        flowid_idx = filter_del.index("flowid")
        assert filter_del[flowid_idx + 1] == "1:2"

    def test_rollback_qdisc_uses_correct_parent(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="3:")
        rec.status = NetworkInterventionStatus.APPLIED

        with patch.object(engine, "_run_cmd", wraps=engine._run_cmd) as mock_run:
            engine.rollback(rec)

        cmds = _extract_cmds(mock_run)
        qdisc_del = cmds[1]
        parent_idx = qdisc_del.index("parent")
        assert qdisc_del[parent_idx + 1] == "1:3"

    def test_rollback_sets_status_rolled_back(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:")
        rec.status = NetworkInterventionStatus.APPLIED
        result = engine.rollback(rec)
        assert result.status == NetworkInterventionStatus.ROLLED_BACK

    def test_rollback_increments_attempt_counter(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:")
        rec.status = NetworkInterventionStatus.APPLIED
        engine.rollback(rec)
        assert rec.rollback_attempts == 1


# ---------------------------------------------------------------------------
# T3-f: Repeated intervention (same band, different records)
# ---------------------------------------------------------------------------

class TestRepeatedIntervention:
    def test_two_records_with_different_bands(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec1 = _make_record(tc_handle="1:", latency_ms=100.0)
        rec2 = _make_record(tc_handle="2:", latency_ms=200.0)

        r1 = engine.apply(rec1)
        r2 = engine.apply(rec2)

        assert r1.status == NetworkInterventionStatus.APPLIED
        assert r2.status == NetworkInterventionStatus.APPLIED
        assert len(engine._active_records) == 2

    def test_rollback_all_removes_all_records(self):
        engine = NetworkInterventionEngine(dry_run=True)
        for band in (1, 2, 3):
            rec = _make_record(tc_handle=f"{band}:")
            engine.apply(rec)

        assert len(engine._active_records) == 3
        rolled = engine.rollback_all()
        assert len(rolled) == 3
        assert len(engine._active_records) == 0


# ---------------------------------------------------------------------------
# T3-g: Invalid state handling
# ---------------------------------------------------------------------------

class TestInvalidStateHandling:
    def test_verify_on_non_applied_record_does_not_change_status(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:")
        # record is still PENDING (not applied)
        result = engine.verify(rec)
        assert result.status == NetworkInterventionStatus.PENDING

    def test_verify_on_applied_sets_verified(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:")
        rec = engine.apply(rec)
        rec = engine.verify(rec, measured_latency_ms=None)
        assert rec.status == NetworkInterventionStatus.VERIFIED

    def test_verify_precision_check_pass_on_good_measurement(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:", latency_ms=200.0)
        rec = engine.apply(rec)
        # Within 10% error → pass
        rec = engine.verify(rec, measured_latency_ms=205.0)
        assert rec.precision_check_pass is True

    def test_verify_precision_check_fail_on_bad_measurement(self):
        engine = NetworkInterventionEngine(dry_run=True)
        rec = _make_record(tc_handle="1:", latency_ms=200.0)
        rec = engine.apply(rec)
        # >20% error → fail
        rec = engine.verify(rec, measured_latency_ms=300.0)
        assert rec.precision_check_pass is False
        assert rec.status == NetworkInterventionStatus.CONFOUNDED
